### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by am548726** [chonnens/the-berry-patch#1]
# Semantics
## Naming Conventions
- Your html outline has the right heading levels but the names of each header level is a bit confusing when I check at https://gsnedders.html5.org/outliner/. I would suggest you check it out and give those headings a proper name.
- Although you are using placeholder images, I suggest that when using an actual image make sure they are named properly for example hero-lg-ball.jpg or icon-sm-facebook.svg.
- There was a area for your hero section where you use a h1 more than once to get the line break. I think to solve this issue is to use the linebreak tag.
- Lastly, I would make sure your html document is properly formatted.

**Comment by MatthewCThompson** [comment]
There is some css classes that can be given more meaning. I'm guessing some of the classes were brought in but one that stuck out was "single-sentence", you could use something like "intro-sentence" or "preview-sentence".
