### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by slaterjen** [chonnens/the-berry-patch#3]
Overall, I think everything seems to make sense! I have one suggestion for you!

I would make sure all of your button styles are consistent throughout the page. For example your "shop now" button on the hero is a different style from the contact form button.

**Comment by SpicyKeeKay** [comment]
Overall the website looks fine and everything is working properly for the prototype. The only question I have is what is the paragraph after the hero and before the products? Is it a description of the products or a quote?
