### ISSUE TITLE
Cleanliness of Code

### ISSUE THREAD

**Issue by kennybeyer** [chonnens/the-berry-patch#4]
Your guys' code looks pretty good! Easy to follow. I feel like I could jump right in and adjust things myself. I only have a few things to say, I'm not even sure if it's technically about clean code lol. But, you guys have a lot of "px" for sizing fonts and other measurements in your custom.css. Also in your index.html some of your indents are inconsistent, like an opening div won't be on the same line as the closing div. Not a huge deal but I needed to find something. Good Job, buttheads!

**Comment by Valerie-Wissenburg** [comment]
PROFICIENT
I agree with Kenny. So far everything looks good!
HTML:
One question that I had was for your js starting on line 200. I'm not quiet sure if that's correctly placed or if it needs to go in a custom js? If it's correct then just forget the statement but I thought I'd make note of it just in case. Also, you have <br> in your form. Are you sure it's not </ br>?

**Comment by kennybeyer** [comment]
So, yeah. Like Ella just said, you guys, like everyone else, have a lot of folders and documents that you aren't using that you can throw away.

**Comment by kennybeyer** [comment]
looks like the div on 45 needs to be indented since it is nested in the div on 44. Same with line 181.

**Comment by Valerie-Wissenburg** [comment]
One thing I noticed is that on line 29 your class has ="". I'm pretty sure you need a space between the " " so it's a null tag. Or if you forgot to put a class in there– here's your reminder to put one in! :)

**Comment by Valerie-Wissenburg** [comment]
These last 2 comments from me are in HTML by the way.
You also don't have to keep the comment on line 22. If it's not relevant to you, there's no need to have it.
