### ISSUE TITLE
Directory Organization

### ISSUE THREAD

**Issue by elladurham** [chonnens/the-berry-patch#7]
**Satisfactory**
Overall good, but you have some extra files you aren't using and this effects the efficiency of your organization.

**Comment by e-m-durham** [comment]
In your CSS, it seems like you could remove the slick folder and move slick.css and slick-theme.css into the /css/ folder. Currently, they are the only stylesheet in their own folder and you aren't really using any of those other files.

**Comment by e-m-durham** [comment]
Make use of humans.txt, robots.txt, and README.md or don't have them at all.

**Comment by e-m-durham** [comment]
Find out which vendor scripts you want to use and remove the rest.
